# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d949f597ef72e36a5aec8373a41aff4b7b53bc1da1396edbbf7221e7c11f5937307c8ca5859054a1f987b94127b43daa96ac50f8c60121bbd4aa11d040a643bd

test:
  secret_key_base: 6823f697ebcd5176adff495fd83df3a4b940a16fc9ba6777609ee9dbb5b9d4c595a17a4f139d835d51bfc036852aefe4a5f7d2d208a3cde95a4a8faa3207b68c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
